Makes the raw loitering events query parametrizable

diff --git a/scripts/generate_carrier_loitering_events b/scripts/generate_carrier_loitering_events
--- a/scripts/generate_carrier_loitering_events
+++ b/scripts/generate_carrier_loitering_events
@@ -5,14 +5,16 @@ THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
 # source ${THIS_SCRIPT_DIR}/pipeline.sh
 ASSETS=${THIS_SCRIPT_DIR}/../assets
 ARGS=( \
-  SOURCE_RAW_LOITERING_EVENTS \
+  DATE_RANGE \
+  SOURCE_RESEARCH_MESSAGES \
   SOURCE_SEGMENT_INFO \
   SOURCE_SPATIAL_MEASURES \
   SOURCE_COUNTRY_CODES \
   SOURCE_VOYAGES \
   SOURCE_NAMED_ANCHORAGES \
-  SOURCE_SEGS \
+  SOURCE_RESEARCH_SEGS \
   SOURCE_VESSEL_DATABASE \
+  TEMP_DATASET \
   DEST_TABLE \
 )
 
@@ -36,6 +38,12 @@ for index in ${!ARGS[*]}; do
   echo "  ${ARGS[$index]}=${ARG_VALUES[$index]}"
   declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
 done
+
+
+IFS=, read START_DATE END_DATE <<<"${DATE_RANGE}"
+if [ -z $END_DATE ] || [ $END_DATE == $START_DATE ]; then
+  END_DATE=$(date +%Y-%m-%d -d "$START_DATE + 1 day")
+fi
 ################################################################################
 # Force that the destination table exists
 ################################################################################
@@ -61,23 +69,54 @@ fi
 echo "  Events table exists"
 
 ################################################################################
+# First generate the raw loitering events into an intermediate temp table
+################################################################################
+echo "Generating raw loitering events table"
+UUID=$(uuidgen)
+INTERMEDIATE_TABLE="${TEMP_DATASET}.${UUID//-/_}"
+SQL=${ASSETS}/bigquery/events-loitering-events-raw.sql.j2
+jinja2 ${SQL} \
+  -D research_messages=${SOURCE_RESEARCH_MESSAGES//:/.} \
+  -D research_segs=${SOURCE_RESEARCH_SEGS//:/.} \
+  -D start_date=${START_DATE} \
+  -D end_date=${END_DATE} \
+  -D vessel_database=${SOURCE_VESSEL_DATABASE//:/.} \
+  | bq query --max_rows=0 --allow_large_results --replace --destination_table ${INTERMEDIATE_TABLE}
+
+if [ "$?" -ne 0 ]; then
+  echo "  Unable to insert records for table ${INTERMEDIATE_TABLE}"
+  exit 1
+fi
+
+################################################################################
 # Generate the loitering events
 ################################################################################
 echo "Generating loitering events at ${DEST_TABLE}"
 SQL=${ASSETS}/bigquery/events-loitering-events.sql.j2
 jinja2 ${SQL} \
-  -D raw_loitering_events=${SOURCE_RAW_LOITERING_EVENTS//:/.} \
+  -D raw_loitering_events=${INTERMEDIATE_TABLE} \
   -D segment_info=${SOURCE_SEGMENT_INFO//:/.} \
   -D spatial_measures=${SOURCE_SPATIAL_MEASURES//:/.} \
   -D country_codes=${SOURCE_COUNTRY_CODES//:/.} \
   -D voyages=${SOURCE_VOYAGES//:/.} \
   -D named_anchorages=${SOURCE_NAMED_ANCHORAGES//:/.} \
-  -D segs=${SOURCE_SEGS//:/.} \
+  -D segs=${SOURCE_RESEARCH_SEGS//:/.} \
   -D vessel_database=${SOURCE_VESSEL_DATABASE//:/.} \
   | bq query --max_rows=0 --allow_large_results --replace --destination_table ${DEST_TABLE}
 
 if [ "$?" -ne 0 ]; then
   echo "  Unable to insert records for table ${DEST_TABLE}"
+  exit 1
+fi
+
+################################################################################
+# Remove the intermediate results table
+################################################################################
+echo "Deleting intermediate raw loitering events results table"
+bq rm -t -f ${INTERMEDIATE_TABLE}
+
+if [ "$?" -ne 0 ]; then
+  echo "  Unable to remove intermediate table ${INTERMEDIATE_TABLE}"
   exit 1
 fi
 
