Use a destination table instead of temporal table to save carrier vessels in bq. CVP-160

diff --git a/scripts/publish_vessel_info b/scripts/publish_vessel_info
--- a/scripts/publish_vessel_info
+++ b/scripts/publish_vessel_info
@@ -10,8 +10,9 @@ ARGS=( \
   SOURCE_VESSEL_DATABASE \
   SOURCE_COUNTRY_CODES \
   SOURCE_RESEARCH_VESSEL_INFO \
-  TEMP_DATASET \
+  ##TEMP_DATASET \
   TEMP_BUCKET \
+  DEST_TABLE \
   ELASTIC_SEARCH_SERVER_URL \
   ELASTIC_SEARCH_INDEX_ALIAS \
 )
@@ -40,10 +41,10 @@ done
 # Running bigquery query to generate vessel information
 ################################################################################
 echo "Running vessel information query"
-UUID=$(uuidgen)
-TEMP_EXTRACT_TABLE="${TEMP_DATASET}.${UUID//-/_}"
+#UUID=$(uuidgen)
+#TEMP_EXTRACT_TABLE="${TEMP_DATASET}.${UUID//-/_}"
 VESSEL_INFO_QUERY="${ASSETS}/bigquery/vessels-vessel-info.sql.j2"
-echo "  Running query to destination table ${TEMP_EXTRACT_TABLE}"
+echo "  Running query to destination table ${DEST_TABLE}"
 jinja2 ${VESSEL_INFO_QUERY} \
   -D encounter_events=${SOURCE_ENCOUNTER_EVENTS//:/.} \
   -D loitering_events=${SOURCE_LOITERING_EVENTS//:/.} \
@@ -51,40 +52,40 @@ jinja2 ${VESSEL_INFO_QUERY} \
   -D vessel_database=${SOURCE_VESSEL_DATABASE//:/.} \
   -D country_codes=${SOURCE_COUNTRY_CODES//:/.} \
   -D vi_ssvid_by_year=${SOURCE_RESEARCH_VESSEL_INFO//:/.} \
-  | bq query --max_rows=0 --allow_large_results --replace --destination_table ${TEMP_EXTRACT_TABLE}
+  | bq query --max_rows=0 --allow_large_results --replace --destination_table ${DEST_TABLE}
 if [ "$?" -ne 0 ]; then
-  echo "  Unable to run vessel information query into ${TEMP_EXTRACT_TABLE}"
+  echo "  Unable to run vessel information query into ${DEST_TABLE}"
   exit 1
 fi
-echo "  Extracted vessel information into ${TEMP_EXTRACT_TABLE}"
+echo "  Extracted vessel information into ${DEST_TABLE}"
 
 #################################################################################
 ## Export records to json files
 #################################################################################
-echo "Exporting records from $TEMP_EXTRACT_TABLE"
+echo "Exporting records from $TDEST_TABLE"
 TEMP_PATH=gs://${TEMP_BUCKET}/pipe-carrier-portal/publish-vessel-info/$( date -u "+%FT%T.%N" )
 TEMP_EXTRACT_PATH=$TEMP_PATH/bq/*.json.gz
 bq --headless extract \
   --compression=GZIP \
   --destination_format=NEWLINE_DELIMITED_JSON \
-  $TEMP_EXTRACT_TABLE \
+  $DEST_TABLE \
   $TEMP_EXTRACT_PATH
 if [ "$?" -ne 0 ]; then
-  echo "  Unable to extract ${TEMP_EXTRACT_TABLE} to ${TEMP_EXTRACT_PATH}"
+  echo "  Unable to extract ${DEST_TABLE} to ${TEMP_EXTRACT_PATH}"
   exit 1
 fi
-echo "  Exported records from ${TEMP_EXTRACT_TABLE} to ${TEMP_EXTRACT_PATH}"
+echo "  Exported records from ${DEST_TABLE} to ${TEMP_EXTRACT_PATH}"
 
 ################################################################################
 # Delete the temp extract table
 ################################################################################
-echo "Deleting temp extract table ${TEMP_EXTRACT_TABLE}"
-bq rm -t -f ${TEMP_EXTRACT_TABLE}
-if [ "$?" -ne 0 ]; then
-  echo "  Unable to delete the temp extract table ${TEMP_EXTRACT_TABLE}"
-  exit 1
-fi
-echo "  Deleted the temp extract table ${TEMP_EXTRACT_TABLE}"
+#echo "Deleting temp extract table ${TEMP_EXTRACT_TABLE}"
+#bq rm -t -f ${TEMP_EXTRACT_TABLE}
+#if [ "$?" -ne 0 ]; then
+#  echo "  Unable to delete the temp extract table ${TEMP_EXTRACT_TABLE}"
+#  exit 1
+#fi
+#echo "  Deleted the temp extract table ${TEMP_EXTRACT_TABLE}"
 
 ################################################################################
 # Download files locally
